### ISSUE TITLE
Electrum Portable wallet - 3.2.2 - <class 'OverflowError'>: int too long to convert

### ISSUE THREAD

**Issue by silverdelange** [vertcoin/electrum-vtc#103]
Hi.

I am using Electrum Portable wallet and when I want to send coins to a cold address it gives me the following error;
argument 1: <class 'OverflowError'>: int too long to convert

Windows 10 64 bit.

Any advice will be appreciated.

Thank you.

**Comment by metalicjames** [comment]
Closing as duplicate of #99
