### ISSUE TITLE
Wallet Not Connected

### ISSUE THREAD

**Issue by james-ingold** [vertcoin/electrum-vtc#104]
Hello, 

I'm on Electrum-VTC 3.2.2 on macos 10.14 and cannot get connected. I've tried unchecking and checking the select server automatically and using specific servers but nothing is working and it still says Not connected. Use proxy is unchecked. 

Status: Not Connected
Server: None
Blockchain: 921311 blocks

**Comment by newuser20180929** [comment]
Hello, 

since yesterday, September 28th, I have the same problem. I am using the Electrum Vertcoin wallet 3.2.2 on Windows 7.

On the other hand, the Electrum Bitcoin wallet (same environment) works without any difficulty.

Regards.

**Comment by metalicjames** [comment]
Both uk1.vtconline.org and fr1.vtconline.org are up. Can you confirm that you can connect to them?

**Comment by james-ingold** [comment]
Thanks, I was able to connect to uk1.vtconline.org and synchronize
