### ISSUE TITLE
argument 1: <class 'OverflowError'>: int too long to convert

### ISSUE THREAD

**Issue by poolminer1907** [vertcoin/electrum-vtc#106]
I am trying to sign a Vertcoin transaction in Electrum-VTC so it can be broadcast.  The transaction has a large amount of inputs (1062) and results in an argument 1: <class 'OverflowError'>: int too long to convert.  When I load the transaction from a file, click send, and enter in the password the error is produced.  Is there any work rounds or fixes for this issue? Thank you.

**Comment by metalicjames** [comment]
If you have too many small inputs you'll have to move your private keys into Vertcoin Core, and use its utxo selection function to manually select your inputs.
