### ISSUE TITLE
Misspelled text in the portable install wizard

### ISSUE THREAD

**Issue by nathancrone** [vertcoin/electrum-vtc#11]
Under "How do you want to connect to a server?" the prompt partially reads "...The servers all fulfil...". It should read "...The servers all fulfill...". I know its nitpicky. Just trying to help make the product a bit more professional looking. Thanks for the work!

**Comment by pknight007** [comment]
I think they're both correct: https://www.grammarly.com/blog/fulfil-fulfill/ . (Click the go to blog post at the bottom to pass the annoying ad ;) )

Fulfill is more commonly used in US; fulfil in the UK, ...

**Comment by nathancrone** [comment]
Sorry. Well, I guess I'm the one that isn't looking professional now. Thanks for the reply.

**Comment by pknight007** [comment]
Hey, you don't seem any less professional to me! I'm pretty glad someone is looking over the client with a detailed eye, and is willing to submit issues for things they think are not right.  The end result will be a better client for everyone IMO. If you notice anything else, let me know.  
The issue I've got to get to at some point is this high CPU usage/speed at startup and not shutting down quickly/cleanly.  I've been busy on the refreshed look though. 
@metalicjames I think we can close this issue.
