### ISSUE TITLE
hundreds of transactions verified are not verified and they don't show any transaction.

### ISSUE THREAD

**Issue by yrrmn** [vertcoin/electrum-vtc#114]
hundreds of transactions verified are not verified and they don't show any transaction. They show a date but the amount is 0.0000 and I cannot get any info from them... more tan 25 vtc coins missing.
![vtc wallet](https://user-images.githubusercontent.com/51890652/59569625-a9cb3980-908c-11e9-8ea3-8d2de3c25caa.png)

**Comment by metalicjames** [comment]
Vertcoin hard forked earlier this year so you will need to update your Electrum-VTC to version 3.3.1.
