### ISSUE TITLE
error with pip

### ISSUE THREAD

**Issue by Mahuro** [vertcoin/electrum-vtc#118]
Hi,
I am trying to recover my wallet after updating UBUNTU, but I get this error, any suggestions please? Thanks!
 
The directory '/home/mahuro/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/mahuro/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting dns
  Could not find a version that satisfies the requirement dns (from versions: )
No matching distribution found for dns

**Comment by maxweisspoker** [comment]
Try running the following commands:

$ sudo rm -rf /home/mahuro/.cache/pip/
$ sudo chown -R mahuro:mahuro /home/mahuro/.cache/

Then update your system.  Then reboot.  Then try installing with pip again.

**Comment by metalicjames** [comment]
Closing because this is not an issue specific to electrum-vtc,
