### ISSUE TITLE
Unable to import private key on first startup

### ISSUE THREAD

**Issue by vegardw** [vertcoin/electrum-vtc#12]
When starting Electrum-VTC for the first time, you have the option "Use public or private keys" when creating the default wallet.

I got the private key for one of my addresses using 'dumpprivkey' in vertcoin-qt, but Electrum-VTC doesn't seem to verify the key correctly, so the "Next" button isn't enabled, and I cannot import the key.

There is also a reference to Litecoin left in the help text

![image](https://user-images.githubusercontent.com/7224004/26937992-3adf9778-4c73-11e7-846f-ba52fd162be9.png)

**Comment by metalicjames** [comment]
You'll need to convert the private key into a different format for Electrum to understand it. Use this page: https://walletgenerator.net/?currency=Bitcoin and enter the private key under the "wallet details" tab and copy the hex value under the header "Private Key Hexadecimal Format". Paste that value also under the "wallet details" tab here: https://walletgenerator.net/?currency=vertcoin and use the value under the header "Private Key WIF" to import into Electrum. When you're done you should end up with a value starting with 7.

**Comment by pknight007** [comment]
7d7926a1d257f121e12416fee2a8b0fdc0f52765 , on the vtcgui branch, addresses the Litecoin reference
