### ISSUE TITLE
Wallet doesn't connect to any servers

### ISSUE THREAD

**Issue by ivanaponi** [vertcoin/electrum-vtc#120]
Wallet doesn't connect to any servers

It's like there is not a single server to connect to, the server list is just empty for hours

Is this wallet dead?

**Comment by metalicjames** [comment]
Both uk1.vtconline.org and fr1.vtconline.org should be up and running. Feel free to reopen if there's still a problem.

**Comment by marciopitombeira** [comment]
The same thing happens to me

**Comment by marciopitombeira** [comment]
The same thing happens to me

**Comment by marciopitombeira** [comment]
How do I redeem my crypts if I can no longer connect to any server?
