### ISSUE TITLE
Wallet not connected

### ISSUE THREAD

**Issue by newuser20180929** [vertcoin/electrum-vtc#121]
Hello,

I'm on Electrum-VTC 3.3.1 and cannot get connected since last Tuesday. Both uk1.vtconline.org and fr1.vtconline.org as well as all other listed servers are obviously unavailable.

Status: Not Connected
Server: None
Blockchain: 1423929 blocks

**Comment by metalicjames** [comment]
I just restarted both servers, can you connect now?

**Comment by newuser20180929** [comment]
Yes, Sir, thank you so much. Both, uk1.vtconline.org and fr1.vtconline.org, are available today. 
Thanks, James, stay with us.

**Comment by jkornwitz** [comment]
Seeing the same thing now. Can't connect to any servers.

**Comment by newuser20180929** [comment]
> 
> 
> Seeing the same thing now. Can't connect to any servers.

fr1.vtconline.org is available now.
