### ISSUE TITLE
Unable to pay

### ISSUE THREAD

**Issue by 5stones1sling** [vertcoin/electrum-vtc#123]
I am trying to send coins to another wallet but I am getting error: Server did not answer.

I see a red dot on the bottom right. Occasionally it turns green but goes to red again after 10-20 seconds.

**Comment by newuser20180929** [comment]
> 
> 
> I am trying to send coins to another wallet but I am getting error: Server did not answer.
> 
> I see a red dot on the bottom right. Occasionally it turns green but goes to red again after 10-20 seconds.

fr1.vtconline.org is available now, try again.

**Comment by metalicjames** [comment]
See #124
