### ISSUE TITLE
Cant connect to any servers

### ISSUE THREAD

**Issue by CostaPasta** [vertcoin/electrum-vtc#124]
Ive tried to connect manually and have tried fr1.vtconline.org but nothing works. The wallet was working fine a couple days ago

**Comment by metalicjames** [comment]
Since the Verthash fork electrum-vtc is no longer supported. You'll need to export your private keys from electrum into Vertcoin Core in order to spend.

**Comment by CostaPasta** [comment]
How do I import the private keys into vertcoin core from the exported json
file from electrum?

**Comment by newuser20180929** [comment]
Select the pull-down menu "Wallet", then select "Private Keys", thereafter "Export". Enter your wallet password. Finally, you are able to export your addresses and keys into a .csv or .json

**Comment by CostaPasta** [comment]
I got the .json I just don’t know how to import the private keys in the
vertcoin core wallet, thanks for your help.

**Comment by newuser20180929** [comment]
That is the remaining problem, and unfortunately, I can't resolve it up to now. :-(

**Comment by CostaPasta** [comment]
No problem, thanks!

**Comment by koenhoeijmakers** [comment]
So there is no way to import the electrum wallet?

**Comment by CostaPasta** [comment]
Go to your electrum wallet and download your private keys. You can import
them in the vertcoin core console you’ll have to do this for all your
private keys, you should get a null value if it works correctly. This took
a bit of time, but I was able to successfully transfer them. Here’s what
one of the devs told me:

How to export private keys from Electrum and import into Vertcoin-Core

First, export your private keys from Electrum that have balances.

Wallet > Private keys > Export

Once Vertcoin-Core is synced, import the private keys one by one. Window >
Console, then run the command below, replacing myprivatekey with that from
Electrum:

importprivkey myprivatekey

The returned phrase will be null  Wait for Core the rescan.  All funds held
by your key will be imported once finished.
