### ISSUE TITLE
How to build a Windows installer

### ISSUE THREAD

**Issue by fujicoin** [vertcoin/electrum-vtc#15]
Hi metalicjames,

I'm motty@fujicoin.org.

Could you tell me how to build a Windows installer?
OS: ubuntu 14.02 or 16.04 or windows, 32bit or 64bit?
Wine virsion: 16. 17. 18.?
   On ubuntu, I can not find out wine-1.7.18. There is only 16., 18.

Will it work as described on the page below?
https://github.com/spesmilo/electrum/tree/master/contrib/build-wine

Thanks,
motty

**Comment by fujicoin** [comment]
Hi metalicjames,

I completed it.

Thanks!

**Comment by metalicjames** [comment]
Did you manage to compile the latest version in the repo? I have been trying unsuccessfully to produce a binary that will run.
