### ISSUE TITLE
Can not send transaction

### ISSUE THREAD

**Issue by robv60** [vertcoin/electrum-vtc#19]
I have been trying for hours to send VTC to Bittrex and on every attempt i receive the error "Server did not answer."  I had no issues receiving my VTC from shapeshift. I have tried different servers and different fees to no avail. This is costing me time and money. What gives?

**Comment by pknight007** [comment]
The 2 servers currently working are:

1. fr1.vtconline.org
1. vtc.horriblecoders.com

Can you try those individually from the network dialog and report back? Your blockchain tab should say a height bigger than 777480 if you are fully caught up. (Give it some time if not)

**Comment by robv60** [comment]
It worked once the wallet finished syncing. Im a fuck tard.
