### ISSUE TITLE
Not Connected

### ISSUE THREAD

**Issue by masakenji** [vertcoin/electrum-vtc#21]
Hello,
Server was connected earlier but currently not connected in the last few hours. Google search resolutions did not help fix the issue.

**Comment by mrfearless** [comment]
I found that each i use it i have to delete blockchain_headers file before starting app. If i dont delete that file and let it redownload i get not connected in the status bar. Still shows transactions as not verified regardless of anything i do.

**Comment by metalicjames** [comment]
Is this still an issue?

**Comment by masakenji** [comment]
This is no longer an issue. Thank you. I simply re-installed it.

**Comment by masakenji** [comment]
No longer an issue. I simply re-installed it. Cheers.
