### ISSUE TITLE
New Electrum Version 2.9.3.1. Wont Open

### ISSUE THREAD

**Issue by jdomsky** [vertcoin/electrum-vtc#23]
After I download the file my windows can not open the file type?

**Comment by jdomsky** [comment]
So I got the file open using WinZip, but I still do not see where to begin the wallet setup?

**Comment by metalicjames** [comment]
We're currently still working on Windows and MacOS builds of Electrum for version 2.9.3.1. The package you downloaded is for Linux. Use the previous version for now.

**Comment by jdomsky** [comment]
Thanks for getting back to me so quickly James, much appreciated! Do you think im safe to store/hold my VTC long term on the Web Wallet in Vertpunk, or do you recommend Electrum? Thanks.

**Comment by metalicjames** [comment]
I would recommend you use the Core wallet: https://github.com/vertcoin/vertcoin/releases, or a paper wallet: https://vertaddress.org/.

**Comment by jdomsky** [comment]
Thanks man, much appreciated! Im looking forward to the continual growth of Vertcoin, and im looking forward to the big things coming. Keep up the great work!
