### ISSUE TITLE
Can't send to Segwit address

### ISSUE THREAD

**Issue by ianyanian** [vertcoin/electrum-vtc#30]
![electrum_segwit](https://user-images.githubusercontent.com/11296219/31732479-a54f2d08-b406-11e7-83ac-47e1944f170e.JPG)

**Comment by metalicjames** [comment]
This is actually a pay-to-script-hash address, not a SegWit address. The label Ledger have given it is confusing/misleading. But I agree, this is confirmed, working on it. In the meantime, just use a normal 'V' prefixed address to send your coins to your Ledger.

**Comment by o-Epictetus-o** [comment]
Ok, I just came across this when I was about to send my coins to my nano s. So is it wrong in Ledger App or what? I am definitely confused.

**Comment by metalicjames** [comment]
It's a bug in Electrum. Using the pay to script hash address works in Core.

**Comment by metalicjames** [comment]
Fixed in https://github.com/vertcoin/electrum-vtc/commit/6d58a69f4de66e2d89a2406e203fb5cb1758aa84
