### ISSUE TITLE
Can not connect to Hardware Wallet - Trezor

### ISSUE THREAD

**Issue by nigelarcher** [vertcoin/electrum-vtc#32]
Tried to setup this today and could not get it to detect the Trezor hardware wallet. Reported that the system did not have the correct libraries (python-trezor).

I installed a vanilla Electrum wallet, and it found the trezor fine.

OS: Windows 10.

**Comment by metalicjames** [comment]
Trezor does not currently support VTC, and thus no effort has been put in to making it work with Electrum-VTC. Once Trezor integrates Vertcoin, Electrum-VTC will also be updated.

**Comment by nigelarcher** [comment]
AHh, I was surprised the the option being there.. Might be worth removing it to save confusion ;)

**Comment by nigelarcher** [comment]
Can't contribute a branch, so: 
remove line 126, 127 and 134,135 in lib/base_wizard.py would likely do the job

**Comment by lzsaver** [comment]
https://github.com/trezor/trezor-common/blob/master/coins.json

**Comment by metalicjames** [comment]
https://github.com/vertcoin/electrum-vtc/commit/ae9c0793e94aaf2c1772317a3c7737f42687490d

Removed the option
