### ISSUE TITLE
Electrum freezes when loading wallet file

### ISSUE THREAD

**Issue by jglongest** [vertcoin/electrum-vtc#34]
Electrum freezes when i type in my encrypted password. I have tried on multiple computers and it does the same exact thing.

**Comment by lumitor2** [comment]
Same for me. After new version there is only window to go for Console or terminate whole app. 
I have Mac OS 10.12.6.

**Comment by metalicjames** [comment]
Does this happen on all versions of Electrum-VTC or just the current one?

**Comment by lumitor2** [comment]
I thought that it is problem of previous version (downloaded 2 weeks ago) so I downloaded new version and got same results :/

**Comment by metalicjames** [comment]
Can you describe exactly what happens preferably with screenshots? In the meantime, you can restore the wallet from the seed it gave you when you first created it.

**Comment by lumitor2** [comment]
There is a screen cast, if it helps you:
https://youtu.be/Jkz-ZRLNTMQ
Will try to restore my wallet. Thanks

**Comment by lumitor2** [comment]
I've tried second backup wallet file and everything is OK now.

**Comment by metalicjames** [comment]
Sounds like this is solved now.
