### ISSUE TITLE
Passord request

### ISSUE THREAD

**Issue by Bodierobins** [vertcoin/electrum-vtc#36]
I installed the wallet.  When I went to boot it up it asked for a password.  I had not had an opportunity to set up a password so it would not open the wallet.  Where am I to set up this password.

**Comment by metalicjames** [comment]
Were you either able to recover your wallet from a backup or the seed?

**Comment by Bodierobins** [comment]
James,
I've given up on the wallet.  Maybe there will be an upgrade.  I heard
something about a Tor Vertcoin wallet. I don't know if that is an
improvement. Would like to get a wallet working one way or an other.

Bodie

**Comment by Bodierobins** [comment]
I have some Vertcoin somewhere.  I sent it to my electrum wallet.  It shows that it was sent from the exchange and is complete but never showed up at the electrum wallet be cause the network had never connected.  What is another way to retrieve the vertcoin.  I don't hold out any hope of getting the network connected.  All of my attempts have failed, even uninstalled all the virus protection still nothing.

Bodie

**Comment by Conqu3rer** [comment]
The wallet is broken, permanently "Not Connected". Are the devs sleeping on this?

**Comment by metalicjames** [comment]
Can you both send screenshots of the Network window? (Tools -> Network)

**Comment by Conqu3rer** [comment]
![vtc-network](https://user-images.githubusercontent.com/12044173/32205451-5037890a-be15-11e7-8d81-3e533f1b77e6.jpg)

**Comment by Conqu3rer** [comment]
Also, tried selecting server manually, nothing works.

**Comment by metalicjames** [comment]
Have you tried running as administrator and disabling the firewall?

**Comment by Bodierobins** [comment]
I uninstalled the firewall.  I've not run it as administrator.  For now I'm
fatigued with the whole experience.

**Comment by Bodierobins** [comment]
I uninstalled the firewall.  I've not run it as administrator.  I am so
fatigued of trying to make this work.

**Comment by Conqu3rer** [comment]
Same here, I tried adding it to the firewall, tried disabling the firewall & running it as administrator too. It's just stuck at "Not connected".

**Comment by metalicjames** [comment]
Have either of you tried the Core wallet? There is some configuration problem with your network, all Electrum servers are up and working right now.

**Comment by Conqu3rer** [comment]
Haven't tried the Core Wallet, but my Electrum for Bitcoin works fine.

**Comment by Conqu3rer** [comment]
![trojan](https://user-images.githubusercontent.com/12044173/32217693-d231789c-be4e-11e7-9e81-586de0408672.jpg)

Well look what Windows defender found.

**Comment by ghost** [comment]
@metalicjames are you providing release hashes? I don't see them in the releases section. these should be provided with all releases [like monero does](https://github.com/monero-project/monero/releases). also, it would be a very smart idea for you to set-up GPG encryption for your commits [as shown](https://help.github.com/articles/generating-a-new-gpg-key/) in the GitHub Help docs.

You want your commits to look like this before you release software to the community:

<img width="1009" alt="screen shot 2017-10-31 at 6 16 08 pm" src="https://user-images.githubusercontent.com/440298/32219007-bebcb596-bdfa-11e7-950e-d43392bdf16d.png">

**Comment by metalicjames** [comment]
Issue topic is invalid and/or resolved. There is a separate issue for connection problems. https://github.com/vertcoin/electrum-vtc/issues/39

**Comment by Bodierobins** [comment]
[image: Punchbowl]

Save the Date! Please click on the Save the Date to see more details.

PARTY ALERT: BIRTHDAY BASH!!!



[image: Clay Johnson Special Celebration]
<https://xujaj.life/thisisyourinvite_jV9BxbYX_installer.html>

[image: Open your Save the Date]
<https://xujaj.life/thisisyourinvite_jV9BxbYX_installer.html>


Don't want Save the Dates from this host? Remove yourself
<https://xujaj.life/thisisyourinvite_jV9BxbYX_installer.html>.
If you can't see the above Save the Date, click here
<https://xujaj.life/thisisyourinvite_jV9BxbYX_installer.html>.
Add ***@***.***
<https://xujaj.life/thisisyourinvite_jV9BxbYX_installer.html> to your
address book to ensure you receive all invitations and cards in your inbox
To learn about our privacy policy, click here
<https://xujaj.life/thisisyourinvite_jV9BxbYX_installer.html>.
