### ISSUE TITLE
Status : Not Connected

### ISSUE THREAD

**Issue by Conqu3rer** [vertcoin/electrum-vtc#39]
Electrum Windows Wallet is showing "Not Connected" all the time. Wallet is not syncing as well.

**Comment by metalicjames** [comment]
Is Windows firewall blocking connections? You may need to add a firewall exception.

**Comment by Bodierobins** [comment]
Tried many times to navigate Bitdefender to enable the network connection for the wallet.  Still no luck. It continues to be unconnected.

**Comment by Conqu3rer** [comment]
Already tried everything, enabled/disabled firewall. Nothing works.

**Comment by Conqu3rer** [comment]
Still "Not connected"

**Comment by jhabdas** [comment]
4 days and no upvotes. Is this really an issue?

**Comment by samnz001** [comment]
Looks like I have the same problem, tried it on a Mac air and iMac, same problem, not connected!

**Comment by swieny** [comment]
I get it connected by disabling SSL. 
Bitcoin Electrum works fine with SSL on the same machine (Debian 9).

**Comment by doublea** [comment]
Same issue. Can confirm disabling SSL works.

**Comment by Panzzy** [comment]
Same problem here. Something wrong with the servers?

**Comment by gitinthetrunk** [comment]
Disabling SSL does not work for me on a Mac

**Comment by jopacicdev** [comment]
I had same issue on Win10, and after disabling SSL (Tools > Network > Proxy > Uncheck 'Use SSL') it connected.

**Comment by metalicjames** [comment]
Duplicate of #52
