### ISSUE TITLE
Electrum vtc 2.9.3.3 stays indefinite time on "unconfirmed"

### ISSUE THREAD

**Issue by VenciVT** [vertcoin/electrum-vtc#41]
After initiating transaction of vtc to confirmed address the status doesn't seem to change for 24 hours already.

Restarting the pc and the wallet doesn't help.

Please advise what to do?

Best regards,
Venci

**Comment by goodc0re** [comment]
Find a solution in issue #33:
https://github.com/vertcoin/electrum-vtc/issues/33

**Comment by metalicjames** [comment]
Duplicate of #33
