### ISSUE TITLE
Electrucm VTC  Not Starting

### ISSUE THREAD

**Issue by alelopezperez** [vertcoin/electrum-vtc#42]
Hi, i recently installed Electrum-VTC via 
sudo -H pip3 install https://github.com/vertcoin/electrum-vtc/releases/download/2.9.3.3/Electrum-VTC-2.9.3.3.tar.gz

and after clicking the app on the ubuntu app list, the program does not start

**Comment by metalicjames** [comment]
Electrum is written in Python 2. You will need to use `pip2`.

**Comment by metalicjames** [comment]
No response for two months, assuming resolved.
