### ISSUE TITLE
Add Release Hashes

### ISSUE THREAD

**Issue by ghost** [vertcoin/electrum-vtc#43]
Given it's possible for tampering to occur over the wire and this is a wallet which holds currency [please consider](https://github.com/vertcoin/electrum-vtc/issues/36#issuecomment-340718617) adding release hashes with every release.

**Comment by ghost** [comment]
Whoops, wrong button. Also, please add GPG encryption to your commits so we know at a glance commits are produced by a unique individual. Otherwise anyone with your email address may push commits as another individual on GitHub.

**Comment by metalicjames** [comment]
We're working on ephemeral builds on our build server that will also provide code signing, it's on my roadmap. As for commits, surely you'd need access to my ssh keys to commit as me, or is there some security loophole in GitHub that I should be aware of?

**Comment by ghost** [comment]
While I'd like to take your word for your use of 2FA, I won't have to if commits are [signed with GPG](https://help.github.com/articles/signing-commits-using-gpg/). I left an example of [what signed commits look like](https://github.com/vertcoin/electrum-vtc/issues/36#issuecomment-340718617) for your review.

**Comment by metalicjames** [comment]
The latest release has signatures for the binaries included.
