### ISSUE TITLE
transactions will not verify

### ISSUE THREAD

**Issue by gitinthetrunk** [vertcoin/electrum-vtc#45]
Updated to 2.9.3.3 and still not verifying. I am on a Mac OS 10.11.6

**Comment by rbish** [comment]
I have 2.9.3.3 as well and last coins received to wallet show but are not verified.  Do they have to be verified?

**Comment by gitinthetrunk** [comment]
I dont know. I think I will try to move the coins to another location and I guess that will tell us.

**Comment by gitinthetrunk** [comment]
Wallet will not connect. Cant do anything

**Comment by gitinthetrunk** [comment]
concerned the whole thing is a scam

**Comment by metalicjames** [comment]
Fixed in e3f90acd
