### ISSUE TITLE
Restore with the seed and lost the last address in list

### ISSUE THREAD

**Issue by Ricotro** [vertcoin/electrum-vtc#46]
PC A) i7 W10 Pro 64bit 16GB ram - PC B) Xeon W10 Pro 64Bit 4GB ram - both with electrum-VTC-2.9.3.3 on board. At the installation time of electrum on the PC B, on the PC A electrum was already installed but not open.
Issue: I made a electrum 2nd installation on PC B) with backup purpose using the seed way to "Clone" PC A) data. On the PC B is missing just the "Replication" of the last address in list. PC A has default nr. 21 Vxxxxxxxxxxxxxxxxx addresses available and on the PC "Clone" you can count just 20.

Best regards
Ricotro
![pc_a](https://user-images.githubusercontent.com/33792406/32988829-84d277a0-cd0c-11e7-8e2d-4dd1c695f5db.jpg)
![pc_b](https://user-images.githubusercontent.com/33792406/32988830-84f503d8-cd0c-11e7-96d5-86f1ac57b46e.jpg)

**Comment by metalicjames** [comment]
Did you use the address that's missing?

**Comment by Ricotro** [comment]
No. But days after installing the wallet on the PC B (Backup PC) the missing address magically appears.

**Comment by metalicjames** [comment]
I imagine that would be the reason then. Electrum won't care about showing you addresses you never used.

**Comment by Ricotro** [comment]
Probably you miss the point: on the installation A there is (default 21 addresses empty), on the "backup" (restored with seed) there is not (default 20 addresses, empty as well).

**Comment by pknight007** [comment]
I tried this in 2.9.3.5 Linux and couldn't reproduce the issue with that version and OS. Given the way Electrum generates addresses from a seed, I don't think we'd be at risk of losing anything here. It would be more a UI quirk, if it still exists in 2.9.3.5, which may eventually get fixed in upstream. Okay to close?

**Comment by Ricotro** [comment]
Yes, I think so.
