### ISSUE TITLE
Issue with receiving? (OSX)

### ISSUE THREAD

**Issue by gu-ma** [vertcoin/electrum-vtc#48]
Hi there,

I sent some VTC from Shapeshift to electrum-vtc using the address found in the "receive" tab but still nothing arrived. It's been a day already so it's a bit weird, the transaction went through just fine apparently on Shapeshift.

Any ideas why?

Thanks,

G.

**Comment by metalicjames** [comment]
Was this resolved by shapeshift?

**Comment by gu-ma** [comment]
Hey, thanks for following up on this. Yes, It was a problem on their side.
