### ISSUE TITLE
Electrum VTC Won't open on win 10 64bit

### ISSUE THREAD

**Issue by F4np** [vertcoin/electrum-vtc#49]
Tried the setup and the portable and the program wont open

**Comment by ariiZona** [comment]
Same issue here. With or without password encryption, the wallet simply does not open, the program suddenly goes in the background and starts using 20% cpu usage and the process gets killed when moving the mouse over the icon in the notification center.

**Comment by metalicjames** [comment]
Are people still having issues with this?

**Comment by Krciii** [comment]
Yes, same issue here.

**Comment by asajosh** [comment]
Same issue here - v2.9.3.6 - ran like a champ for about 8 days, then got a bunch of unverified transactions. Uninstalled, reinstalled, now sitting at the password screen for my wallet, password plugged in, not responding. Any assistance would be appreciated.

**Comment by CZermi** [comment]
Any progress with this issue? Almost end of february and still no response?

**Comment by metalicjames** [comment]
Have you folks been mining into Electrum by any chance?

**Comment by asajosh** [comment]
I was yes. I was new to vertcoin at the time and Electrum came recommended
for mining. Since the issue got worse I have moved my coins and found more
mining friendly wallet options.

**Comment by nicolaevladescu** [comment]
Mine opens after 25 minutes but all my funds are unmatured and can't move the funds to vertcoin core and every window from the menu i open makes the program unresponsive again.

I am using windows 10 pro 64 bit and `electrum-vtc-2.9.3.6-windows.exe`

Is there any way to export the key so we could use it in vertcoin core? My funds are stuck in `electrum-vtc`, i see no way to recover or move them.

**Comment by metalicjames** [comment]
@nicolaevladescu were you mining into the wallet? If so, you'll need to move the private keys to Vertcoin Core. You can dump the keys from Electrum-VTC by going to `Wallet -> Private Keys -> Export` on the top menu bar. 

These can then be imported into Vertcoin Core using the following instructions: https://bitcoin.stackexchange.com/questions/5941/how-do-i-import-a-private-key-into-bitcoin-core

**Comment by nicolaevladescu** [comment]
Yes i was mining into it, i know it's not recommended and i will mine to vercoin core.

Accessing any item from any tab menu makes it "Not Responding" again.

**Comment by metalicjames** [comment]
Issue several months old and relates to an Electrum-VTC version that's long since been deprecated.
