### ISSUE TITLE
Electrum asking for vtc_scrypt module in Linux mint

### ISSUE THREAD

**Issue by pedronavajo** [vertcoin/electrum-vtc#50]
I am trying both electrum-vtc and the version for Tor network. In both cases works fine in W64, however when trying to run in Linux Mint I get the following error:
`Traceback (most recent call last):
  File "./electrum-vtc", line 95, in <module>
    imp.load_module('electrum_vtc', *imp.find_module('lib'))
  File "/home/juan/Electrum-VTC-2.9.3.3-tor/lib/__init__.py", line 6, in <module>
    from network import Network, pick_random_server
  File "/home/juan/Electrum-VTC-2.9.3.3-tor/lib/network.py", line 43, in <module>
    import blockchain
  File "/home/juan/Electrum-VTC-2.9.3.3-tor/lib/blockchain.py", line 37, in <module>
    import vtc_scrypt
ImportError: No module named vtc_scrypt`

Where do I get the vtc_scrypt module from?

**Comment by ilius** [comment]
Have you tried this?

    pip install vtc_scrypt

Via https://pypi.org/project/vtc_scrypt/

**Comment by pedronavajo** [comment]
that was an easy one!! Thanks for the heads up. I should have thought about it earlier. Indeed, after installing the library, everything works smooth!! thanks
