### ISSUE TITLE
Electrum-VTC Error everytime I enter encryption

### ISSUE THREAD

**Issue by mello1234** [vertcoin/electrum-vtc#51]
Won't even allow me to recover from seed because the top of the bar says electrum installer.

**Comment by ghost** [comment]
Same problem here. Anyone?

**Comment by ghost** [comment]
![screen shot 2017-12-11 at 12 24 43 pm](https://user-images.githubusercontent.com/34423560/33845158-7df62c9a-de70-11e7-9624-640f6bca9297.png)
![screen shot 2017-12-11 at 12 24 51 pm](https://user-images.githubusercontent.com/34423560/33845162-861ca638-de70-11e7-8920-1b73c808a21f.png)

**Comment by ghost** [comment]
Can anyone help? Or point me in the right direction?

I have looked everywhere for a solution but cannot find one.

**Comment by metalicjames** [comment]
Your wallet file must've become corrupted. Were you able to restore it from the seed?
