### ISSUE TITLE
Electrum not connected

### ISSUE THREAD

**Issue by hosseinmor1** [vertcoin/electrum-vtc#53]
for some reasons, Electrum is not getting connected.
removed the software and reinstalled, did not work. used different computers and different networks.
any idea?

**Comment by stefonarch** [comment]
Duplicate of https://github.com/vertcoin/electrum-vtc/issues/52
Selecting manually and   proxy → disable SSL solves, but disabling ssl not looks like a very cool thing to do...

**Comment by hosseinmor1** [comment]
Thanks

**Comment by gitinthetrunk** [comment]
Disabling does nothing for me on Mac

**Comment by stefonarch** [comment]
Disabling "select server automatically" and uncheck ssl you have to choose manually (right-click) one of the servers, the only one working was one from coinomi.

But frankly said I don't like that at all, it is a private company and was already in trouble for not using ssl for communications.

I saw that vertcoin electrum tor wallet connects well, still manually selecting one of the servers but with SSL checked.

**Comment by metalicjames** [comment]
Duplicate of #52
