### ISSUE TITLE
Unable to connect to electrum-vtc

### ISSUE THREAD

**Issue by kumarbellamkonda** [vertcoin/electrum-vtc#56]
Hi,
I am unable to connect to electrum vtc even though  i have did unselected ssl,server and tried to load each avilable server manually.

**Comment by jasonjalves** [comment]
I am having the same issue.  I have already updated my firewall settings to allow permission for electrum

**Comment by metalicjames** [comment]
Is this still an issue for you? There are at least three servers up and available via SSL at present.

**Comment by metalicjames** [comment]
Duplicate of #52
