### ISSUE TITLE
unresponsive

### ISSUE THREAD

**Issue by David202** [vertcoin/electrum-vtc#57]
program went unresponsive been running just fine but now when i put in my password it just crashes tried uninstalling and reinstalling with no change any help would be appriciated

**Comment by metalicjames** [comment]
Can you restore the wallet from the seed?

**Comment by petrkr** [comment]
I think it is beauce first downloading of blockchain haders, regarding to log

```
[fr1.vtconline.org] requesting chunk 411
[profiler] on_update 0.0004
[profiler] verify_chunk 10.4967
[fr1.vtconline.org] requesting chunk 412
[profiler] on_update 0.1199
[profiler] verify_chunk 9.1735
[fr1.vtconline.org] requesting chunk 413
[profiler] on_update 0.0349
[profiler] verify_chunk 9.4511
..
..
..
[fr1.vtconline.org] requesting chunk 423
[profiler] on_update 0.0006
[profiler] verify_chunk 11.6173
[fr1.vtconline.org] catch up done 854545
```

After like 5-10 minutes it stops eat 100% cpu and starts to be responsible.

Devs, can you fix this issue ?
 - download initial blockchain headers from trusted store like original electrum do
 - optimize profiler, so it will not block GUI threads

petr

**Comment by metalicjames** [comment]
Duplicate of https://github.com/vertcoin/electrum-vtc/issues/49
