### ISSUE TITLE
no transaction found on vtc network

### ISSUE THREAD

**Issue by uswer80** [vertcoin/electrum-vtc#59]
I made a transaction from electrum wallet to ledger nano s, but my transaction has not been confirmed and the vtc network does not see it. I tried to deduce 12.94 vtc with the commission of 0.005vtc. help with this transaction: 24b25f5122b09fa07b5c53a3e7da81682275a3daef5ddba4501fa5687b65dbe4

**Comment by metalicjames** [comment]
This is a problem with Ledger, not Vertcoin. You will need to contact them to figure out what went wrong on their end with the transaction.
