### ISSUE TITLE
Crashing/Unresponsive

### ISSUE THREAD

**Issue by lzyPERFECTION** [vertcoin/electrum-vtc#61]
I have been mining to my electrum VTC wallet for about a week and now it crashes every time I enter my password. I still have access to my money if I regenerate my wallet from my seed but now when I try to transfer money it locks up and becomes unresponsive. 

Any thoughts on how to fix these issues? I read that you shouldn't mine to these wallets after I already did that so hopefully there is a way to retrieve my VTC. 

I'm running windows 10 64bit, I have used the install version and the .exe version and had the same issue. I have tried reinstalling a few times, I've tried previous versions and I have deleted my config file in hopes that would change something. I would happily try anything you guys come up with. 

Thanks for the help.

**Comment by metalicjames** [comment]
You will need to export the private keys from Electrum into Core to be able to spend these mined coins.
