### ISSUE TITLE
Electrum wallet password not working

### ISSUE THREAD

**Issue by showmaster2k** [vertcoin/electrum-vtc#62]
Hello,

            I created my electrum-vtc wallet a couple of days ago and I transfered some vertcoins to my wallet. All well, transaction made. Logged off and logged on yesterday, everything ok.
Today when I wanted to log in to my wallet, it says the password (word sequence) is incorrect so I cannot access my wallet even though I haven't changed anything at all.

Any opinions? 

Thank you!

**Comment by ilius** [comment]
I think the password you need to enter each time, is different from that sequence of 12 words. That password is probably shorter (like a normal password).

**Comment by metalicjames** [comment]
@ilius is correct, your seed is different from your password. You'll need your wallet password to unlock the wallet.
