### ISSUE TITLE
Electrum-VTC-TOR 2.9.3.3 - Transaction with 139 confirmations (and counting) not verified

### ISSUE THREAD

**Issue by titan49er** [vertcoin/electrum-vtc#63]
My Electrum-VTC-TOR 2.9.3.3 on macOS 10.12.6 is showing my transactions but they're "Not Verified" even though the blockchain explorer shows 139 confirmations and counting. The previous ticket for this problem was closed.

How do I fix this?

**Comment by metalicjames** [comment]
Duplicate of #58
