### ISSUE TITLE
electrum wallet has not received my coins.

### ISSUE THREAD

**Issue by brandonkgreene** [vertcoin/electrum-vtc#65]
Coinbase says sent and confirmed but my litecoin is not showing up in my wallet

**Comment by metalicjames** [comment]
This wallet is for Vertcoin not Litecoin, I think you are in the wrong place.

**Comment by brandonkgreene** [comment]
--------------------------------------------
On Wed, 12/27/17, James Lovejoy <notifications@github.com> wrote:

 Subject: Re: [vertcoin/electrum-vtc] electrum wallet has not received my coins. (#65)
 To: "vertcoin/electrum-vtc" <electrum-vtc@noreply.github.com>
 Cc: "brandonkgreene" <brandonkgreene@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Wednesday, December 27, 2017, 7:02 PM
 
 This wallet is for Vertcoin not
 Litecoin, I think you are in the wrong place.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
 
 Yes I was trying to convert litecoin into vertcoin via shape shift and somehow I think it went directly to the wallet instead of going through shapeshift. Under the Fiat section there are many different coins that you can choose from, so I changed that to litecoin shouldn't the litecoin still show up? How can I retrieve it or send it back to my account in coinbase?
