### ISSUE TITLE
Missing transactions after synchronization

### ISSUE THREAD

**Issue by std23** [vertcoin/electrum-vtc#68]
I am currently using electrum wallet v. 2.9.3.3 .Today I had numerous confirmed transactions and I had around 2.5 VTC .In a few seconds synchronization started and after it finished I was left with around 0.5 VTC and the records for all transactions in the last 11 hours were missing.Before synchronization there was message "laggy server" or something like that in the bottom left corner of the wallet.This seems to be a serious problem.I guess it is a server side related.Is there a chance to receive my coins after another synchronization?

**Comment by metalicjames** [comment]
If you leave the wallet open for a little while it should sync and show you your coins. What block height does it show under Tools -> Network?

**Comment by std23** [comment]
852243 blocks.Leaving wallet open for more time didn't give a result.

**Comment by metalicjames** [comment]
Hmm, do the transactions show up on the block explorer?

**Comment by std23** [comment]
According to the "Total received" field in the blockchain explorer the transactions about the missing coins had never happened,in other words the total received coins number is short of around 2 coins.

**Comment by metalicjames** [comment]
If the transactions never occurred then it makes sense that Electrum-VTC wouldn't know about them.

**Comment by std23** [comment]
The transactions DID occurre,All transactions in the wallet were CONFIRMED.As I was watching the wallet UI,a syncronisations started.After the syncro finished,the transactions from the last 11 hours were erased and the coins that came with them were taken from my balance.

**Comment by metalicjames** [comment]
So the coins are/are not on the block explorer in their expected addresses?

**Comment by hieupraha** [comment]
it so much prolem with electrum vertcoin wallet . not verifily , not connected . Fix it pls !!!!!! i cant sned any my VTC from electrum wallet !!!!

**Comment by metalicjames** [comment]
There are at least 4 electrum servers up right now. Can you still not connect to any?
