### ISSUE TITLE
Please FIX macOS

### ISSUE THREAD

**Issue by ottodevs** [vertcoin/electrum-vtc#69]
The installation instructions for macOS are insufficient or wrong, we have no google/protobuf package in homebrew so it's failing when trying to make_packages:

![image](https://user-images.githubusercontent.com/5030059/34515793-22f6d400-f074-11e7-90ea-187059ecd390.png)

Also the setup-release command is failing hard.

![image](https://user-images.githubusercontent.com/5030059/34515830-4d4e8ab8-f074-11e7-8b3b-fd57b6150bec.png)

Another thing is, why are homebrew user forced to use SUDO to run setup-release? I never need to do that with other python programs, please check it.

Happy new year and thanks for the hard work!

PS: My system and dependencies are up-to-date (macOS 10.13.2).

**Comment by metalicjames** [comment]
I agree this is far too hard. It took me several hours today to figure out how to build it for Mac (it requires some hacking). I will figure out how best to update the repo to make it easier. 

In the mean time, I posted an OS X binary for the latest release.

**Comment by ottodevs** [comment]
I achieved to run it by activating a python virtual environment, still not very clear to run it.

**Comment by philmb3487** [comment]
What's more the release for macOS has the GUI all messed up, the buttons have no borders, etc.

**Comment by metalicjames** [comment]
macOS build is more straightforward with the latest version.
