### ISSUE TITLE
After updating Electrum wallet to 2.9.3.5, version number still says 2.9.3.4

### ISSUE THREAD

**Issue by Vertimodo** [vertcoin/electrum-vtc#71]
Hi there,
Just noticed a small detail. After updating my electrum wallet version 2.9.3.4 to 2.9.3.5, the title bar still shows the version to be 2.9.3.4
And i'm sure I updated to the latest version ;-) No biggy, just thought I'd let you guys know.

With kind regards, Vertimodo

**Comment by metalicjames** [comment]
Apologies, the binaries have been fixed.
