### ISSUE TITLE
New release v2.9.3.5 for linux don't work

### ISSUE THREAD

**Issue by zoebutter** [vertcoin/electrum-vtc#74]
I have tried many times but Linux version don't work.
It does not allow installation

the command I gave is the following: sudo python3 setup.py install

did I do something wrong?

This is the first time I try to install electrum-vtc on my linux pc. I installed other electrum wallets without problems, but with Vertcoin it's the first time. So I didn't have the old version, this is the first one I downloaded.

**Comment by ilius** [comment]
It runs with python2, so you need to install it with python2:
`sudo python2 setup.py install`

The command `python` (as mentioned in README) points to python2.7 in most of Linux distributions (except Arch)

**Comment by zoebutter** [comment]
I tried and it still doesn't work.

What appears after typing the command "sudo python2 setup.py install" is:

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ImportError: No module named setuptools

**Comment by zoebutter** [comment]
I have resolved!

But I don't used the python2 command. I used another command with pip and then I have runs ./electrum-vtc

But now I have another problem, I have downloaded the version 2.9.3.5 but the launched program says 2.9.3.3

I will open a new post for this
