### ISSUE TITLE
Downloaded Electrum Linux wallet 2.9.3.5, version number says 2.9.3.3

### ISSUE THREAD

**Issue by zoebutter** [vertcoin/electrum-vtc#75]
I have dowloaded today for the first time the Electrum-VTC wallet for Linux 2.9.3.5.

I didn't have previous versions on my pc.

When I launch the program, version number says 2.9.3.3  (That is two previous versions).

Please let me know if it's safe to use it.

**Comment by pknight007** [comment]
The github releases download (electrum-vtc-2.9.3.5.tar.gz) has the CORS commit we merged. You can verify you have that file by checking the signature with gpg:

`gpg --keyserver keyserver.ubuntu.com --recv-keys 0x04e9bcfb4e777ca3`

`gpg --verify electrum-vtc-2.9.3.5.tar.gz.sig electrum-vtc-2.9.3.5.tar.gz`
