### ISSUE TITLE
Need help With electrum-vtc-2.9.3.5-windows-setup.exe 53 MB

### ISSUE THREAD

**Issue by ali6000** [vertcoin/electrum-vtc#78]
Hi i downloaded electrum-vtc-2.9.3.5-windows-setup.exe but when i run the wallet it dont get start to connect to network and get sync why????? and network sign always is red how can ake it connect to network ?????

and a question, i have a few VirtaPay coins from 2013 and have a Private Key for it and heard that i can transfer it to virtacoin and spend it how can i do that ?????

**Comment by ali6000** [comment]
anyone can help me?????

**Comment by ilius** [comment]
This is a Vertcoin wallet. Not related to VirtaCoin nor VirtaPay!

**Comment by metalicjames** [comment]
Not related to VTC.
