### ISSUE TITLE
electrum vtc wallett

### ISSUE THREAD

**Issue by valjames** [vertcoin/electrum-vtc#88]
sent 225 vtc to exodus (send was immediate) wallet. Electrum   history did not update in wallet.  How do i update wallet?
Also then I broadcasted another 225 to exodus and cannot find them on network or in Wallet history 
 When I broadcast now it says network error information missing

WHat can I do to update wallet history and send more Vertcoin out. I am stuck and Tor Browser network is connected
Do i need to update to new version. I see three windows updates which one do i use? see below:
 electrum-vtc-2.9.3.6-windows-setup.exe.sig
32.6 MB electrum-vtc-2.9.3.6-windows.exe
543 Bytes electrum-vtc-2.9.3.6-windows.exe.sig

**Comment by metalicjames** [comment]
You should use this one: electrum-vtc-2.9.3.6-windows.exe

**Comment by valjames** [comment]
Thanks James will that fix the problem?

**Comment by valjames** [comment]
update wallet and allow sends?

**Comment by metalicjames** [comment]
Is the Electrum-VTC wallet in sync? You should have a green dot in the bottom right.

**Comment by valjames** [comment]
The Electrum wallet is still synchronizing  I have enclosed the confirmed
transacttion of VTC to EXODUS.Transaction does not show as sent in electrum
wallet. Says nor confirmed due to network rules
Please advise
Valerie James

**Comment by valjames** [comment]
just stopped synchronizing and did not update to new balance
Just an FYI

V  James

**Comment by metalicjames** [comment]
Can you send a screenshot of `Tools -> Network -> Overview`?

**Comment by valjames** [comment]
screen shot of network transaction for  225  VTC to exodus  wallett
 address:  VenMuqSUNaY1TwX7ZwpiCTao4f2ivYs3Rz  TXID
76fdd1d952821e6a7ec9e3fe6e912a06de27af9c0eb5ced03fbc69d7676ebb99

**Comment by valjames** [comment]
network overview says connected to one node         k3lv7zg5xc24u6d2.onion
  873229  Blocks

**Comment by valjames** [comment]
k3lvz7g5xc24u6d2.onion
  873329 Blocks and height..
 Connected to one node.
Select  server automatically.
First e-mail was off on  digit for k3etc

 Had difficulty doing a screen shot

**Comment by valjames** [comment]
James:

here is a copy of the print screen. Sorry it took so long


[image: Inline image 2]

Thank  You
Valerie James

**Comment by metalicjames** [comment]
I can't see the image. You'll have to upload it on the actual github issue, rather than just responding to the email.

**Comment by valjames** [comment]
ok  thanks I will

**Comment by hieupraha** [comment]
[
![8](https://user-images.githubusercontent.com/36520115/36387794-350dbe7e-159a-11e8-9ecc-37db9d38cf03.JPG) alway not responding when i want to send my VTC

](url)

**Comment by hieupraha** [comment]
![7](https://user-images.githubusercontent.com/36520115/36387928-9a412146-159a-11e8-990e-a8ad9848a4cb.JPG)

**Comment by hieupraha** [comment]
![2](https://user-images.githubusercontent.com/36520115/36388158-3d71598a-159b-11e8-8573-46c17a2e0f03.JPG)
or it still signing transaction... i have waiting 10h and still nothing !!!

**Comment by hieupraha** [comment]
someone help me pls !!! its my 2 months mined

**Comment by metalicjames** [comment]
You'll have to send in smaller amounts, the transaction you are trying to send it over 700kb! and the network limit is 100kb.

**Comment by hieupraha** [comment]
![15](https://user-images.githubusercontent.com/36520115/36413663-b775ad60-161f-11e8-997f-7c6e9598ae66.JPG)
thanks :-)

**Comment by hieupraha** [comment]
but when i close wallet and reopen it, i can't enjoin my wallet. it's still not responding !!! how can i fix this problem ?
![16](https://user-images.githubusercontent.com/36520115/36416243-c636691c-1628-11e8-907e-313b13c08a4e.JPG)

**Comment by metalicjames** [comment]
That appears to be a screenshot of the installer?

**Comment by metalicjames** [comment]
Not enough information available to debug.

**Comment by valjames** [comment]
James
Just a question.  When the genesis block happenned in 2014. What town in
USA was Vertcoin  formed in when the genesis block was started.
So what city was Vertcoin formed in?

Thanks ~
Valerie
