### ISSUE TITLE
Installed new wallet version no updates

### ISSUE THREAD

**Issue by valjames** [vertcoin/electrum-vtc#89]
I installed the new wallet  and The wallet has not updated transactions from today and can not send  VTC

Please Advise

What Can I do next?

Thanks

Valerie JAmes

**Comment by metalicjames** [comment]
Please keep to one issue https://github.com/vertcoin-project/electrum-vtc/issues/88

**Comment by valjames** [comment]
I cannot send  VTC from wallet  TYransaction rejected by network rules.  Missing Input is the message

**Comment by valjames** [comment]
I am happy to donate Vertcoin to fix this problem   Just cant send now

Thanks
