### ISSUE TITLE
Crash on linux debian install

### ISSUE THREAD

**Issue by CodersBrothers** [vertcoin/electrum-vtc#9]
At some point in the instalation...
```
Searching for lyra2re2-hash
Reading https://pypi.python.org/simple/lyra2re2_hash/
Reading https://pypi.python.org/simple/lyra2re2-hash/
Couldn't find index page for 'lyra2re2_hash' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for lyra2re2-hash
error: Could not find suitable distribution for Requirement.parse('lyra2re2-hash')
```
Testing in a clean:
Linux 3.16.0-4-amd64 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

**Comment by CodersBrothers** [comment]
After that, trying to run electrum-vtc:

```
Traceback (most recent call last):
  File "/usr/local/bin/electrum-vtc", line 4, in <module>
    __import__('pkg_resources').run_script('Electrum-VTC==2.8.3.2', 'electrum-vtc')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: lyra2re2-hash
```

**Comment by pknight007** [comment]
sudo pip2 install vtc_scrypt
sudo pip2 install https://github.com/metalicjames/lyra2re-hash-python/archive/master.zip

**Comment by CodersBrothers** [comment]
Maybe it's my problem? When I try to put your comands I get this:
```
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```

**Comment by pknight007** [comment]
Are you running with sudo? Not sure what the deal with the IncompleteRead is - pip should download fine.. You can get the package from that URL manually, unzip and run a `python2 setup.py install` as well if you want an alternative.

**Comment by pknight007** [comment]
@CodersBrothers did any of the above suggestions work for you?

**Comment by CodersBrothers** [comment]
Done! Thanks @pknight007  :+1: 

The manual download and install of lyra2re was the solution.

1. I downloaded at https://github.com/metalicjames/lyra2re-hash-python/archive/master.zip
2. Unzip and type inside the folder: python2 setup.py install
3. In the electrum-vtc folder type: python2 setup.py install

After that I have electrum-vtc installed.

I don't know if "vtc_scrypt" its need it, but I don't installed :P

**Comment by CodersBrothers** [comment]
After launch the wallet my CPU is runing at 100%. Seems weird.

**Comment by pknight007** [comment]
The vert hashing will do that for a bit (validating block headers with the lyra/vtc modules you just installed)..  Let it go, then after it's caught up, future runs will be quick and less CPU.

**Comment by CodersBrothers** [comment]
I tried to open again but now the wallet don't connect to the server.  Besides, without stay as connected, the CPU is 100% again, and when I try to close the program do not respond, only closing by terminal.

**Comment by pknight007** [comment]
Trust me, as it is now just leave it and come back later. It will catch up fine, but the process is a bit slow the first time. Once you're caught up, future loads are faster and work as expected.

I think the file it's plowing through is: blockchain_headers in the ~/.electrum-vtc directory.
