### ISSUE TITLE
IMAGEOFNETWORKOVERVIEW

### ISSUE THREAD

**Issue by valjames** [vertcoin/electrum-vtc#91]
JAMES;

Enclosed are the copies of the NetworkOverview that you requested today. They are in three formats. Let me know if you cannot see them I have one Node only.   A synoposis of what they say is:

k3lvz7g5xc24u6d2.onion
873329 Blocks and height..
 Connected to one node. 
Select  server automatically.  

![printscreenimageforjames](https://user-images.githubusercontent.com/36572965/36358344-c331ebc8-14c1-11e8-869f-8860c2096ee8.png)

[VERTCOINPRINYTSCREENFORJAMESINWORD.docx](https://github.com/vertcoin-project/electrum-vtc/files/1735258/VERTCOINPRINYTSCREENFORJAMESINWORD.docx)

![image](https://user-images.githubusercontent.com/36572965/36358357-134fb108-14c2-11e8-9401-b49ee4e00218.png)

**Comment by valjames** [comment]
[VERTCOINPRINYTSCREENFORJAMESINWORD.docx](https://github.com/vertcoin-project/electrum-vtc/files/1735268/VERTCOINPRINYTSCREENFORJAMESINWORD.docx)
WORD FILE AS WELL

**Comment by metalicjames** [comment]
Has it synced now? I restarted that Electrum server which may have helped.

**Comment by valjames** [comment]
yes it has synced all transactions updated. Also installed new version of Tor Browser. Thanks James !! What is the address to donate Vertcoin too?
Valerie James

**Comment by valjames** [comment]
Yes it synced !! I also realized that I had to upgrade the Tor browser to
get the new sync.
Thanks James !!
Where do we send donations?
Cheers !~
Valerie

**Comment by metalicjames** [comment]
https://vertcoin.org/donate/

**Comment by valjames** [comment]
Thank   You Again sent  Vertcoin
Valerie James
