### ISSUE TITLE
Unable to import private key 

### ISSUE THREAD

**Issue by AH1202** [vertcoin/electrum-vtc#94]
Hi,

I have a problem similar to 

https://github.com/vertcoin-project/electrum-vtc/issues/12?_pjax=%23js-repo-pjax-container

but with the difference that I already have my private key starting with 7.

Can anybody help me?
Thx in advance

**Comment by metalicjames** [comment]
Is this still an issue for you with the latest version?

**Comment by AH1202** [comment]
It was an issue with the latest version. I tried an earlier version now and it works!
