### ISSUE TITLE
Unable to install on linux (Debian 9)

### ISSUE THREAD

**Issue by ultimatevert** [vertcoin/electrum-vtc#95]
It seems with the latest release of electrum-vtc I can not install it using the similar method as previous where a electrum-vtc executable in /usr/local/bin as the insructions say to instead just run "pip3 install .[full]" which I did but that did not seem to install electru-vtc only the dependencies. How can I install electrum-vtc to my system?

Why can't the process be similar to Bitcoin and Litecoin? Both BTC and LTC have an electrum-btc.org and electrum-ltc.org website and steps to install using pip3. electrum-vtc is breaking that up streamlined process up and is rather confusing.

**Comment by metalicjames** [comment]
`pip3 install https://github.com/vertcoin-project/electrum-vtc/releases/download/3.1.2/electrum-vtc-3.1.2.tar.gz` worked for me on Xubuntu 16.04. Then I could run it with `electrum-vtc`.

**Comment by ultimatevert** [comment]
I found another way to install it using this command (which is how you install electrum-LTC).

`sudo pip3 install electrum-vtc-3.1.2.tar.gz`

@metalicjames It seems that it did in fact install correctly except because I was upgrading from a previous electrum-vtc installation I thought the electrum-vtc was the old one (in fact it was still the old one, if i ran electrum-vtc in terminal I would get an error and had to manually delete the old electrum-vtc in /usr/local/bin/electrum-vtc)...it seems this method no longer puts electrum-vtc in /usr/local/bin or it is because I ran pip3 without root this time, not sure. It is working now though, was a mistake on my part.

**Comment by ultimatevert** [comment]
Okay so, I was thinking the wrong thing. I thought "pip3 install .[full]" was working for you, including installing dependencies AND electrum-vtc. 

So it seems you have to run 

sudo apt-get install python3-setuptools
pip3 install .[full]

AND then `sudo pip3 install FILENAMEHERE OR URLTOFILENAMEHERE`
(if I dont run with sudo then it makes an electrum-vtc in ~/.local/bin/ which doesn't let me simply type electrum-vtc to run I have to do the full path)

Maybe this should be put into upstream (I see this is a fork of electrum-ltc) or manually added into the electrum-vtc docs?

**Comment by metalicjames** [comment]
Issue was resolved.
