### ISSUE TITLE
Trying to send funds error 71

### ISSUE THREAD

**Issue by ghost** [vertcoin/electrum-vtc#97]
Upgraded to newest Electrum VTC recently and went to send funds to my Trezor.  Upon putting everything in and inputing password once i hit send i get a yellow Triangle with exclamation and 71.  See attached screenshot.  Never seen this before and have done many transactions.

Thanks.

![screen shot 2018-06-25 at 5 17 03 pm](https://user-images.githubusercontent.com/31999006/41876408-b3fd7742-789b-11e8-95ad-f3fd328c71dd.png)

**Comment by moost** [comment]
I have the same problem. 
The same message when trying to send funds or get the private key.
![vert - error 71](https://user-images.githubusercontent.com/40067225/42375161-df059878-8144-11e8-9a02-f808603bd576.PNG)

**Comment by ghost** [comment]
What I did is delete the new version off my computer and went back to old version.  Everything loaded fine and I sent to Trezor.

**Comment by metalicjames** [comment]
@moost were you able to retrieve your funds?

**Comment by philipkozeny** [comment]
@metalicjames heads up: tried the pre-release v3.2.2, exporting my private key I get: "invalid prefix (199) for WIF key (1)" so error 71 seems to be fixed at least in the pre-release

**Comment by moost** [comment]
@metalicjames Yes, thankfully electrum-vtc-2.9.3.6 recognized the private key I got from vertpunk. (It was a strange private key format 7guuKeFAVp..... which then exported successfully in a different format 5Ju3oBNt......)
