### ISSUE TITLE
electrum-3.2.2 pre release is very laggy

### ISSUE THREAD

**Issue by ultimatevert** [vertcoin/electrum-vtc#98]
This is occurring on Windows 7 with the electrum-vtc-3.2.2-rc2-setup.exe installation

Application launches fine but has large delays from when the mouse is hovered over a tab/button or when an tab/button is clicked and an action finally takes place. The delay lasts for about 1-2 seconds rendering the application almost useless. This issue was present in the 3.1.2  so it was not fixed. The issue does not exist on electrum for BTC so it is specific to electrum-vtc.

**Comment by metalicjames** [comment]
Is it possible that the wallet was just synchronizing? Vertcoin's hash function and difficulty adjustment algorithm are more CPU intensive than BTC's so it's expected that the header synchronisation might affect the performance of the application a little but should subside after a while.

**Comment by ultimatevert** [comment]
Hello metallicjames, 

I am writing this to tell you that the "lag" does seem to have been an issue with the wallet still synchronizing. Even after the wallet showed it was done, by showing "Balance" instead of  "Synchronizing" there was still some lag but after I went to Tools > Preferences the lag went away, even if I close electrum-vtc, wait a while, and open it back up to when it synchronizes.

This was tested with electrum-vtc-3.2.2-rc2
