### ISSUE TITLE
Error when sending funds

### ISSUE THREAD

**Issue by edgartv1** [vertcoin/electrum-vtc#99]
I got funds trap because of the following error:

argument 1: <class 'OverflowError'>: int too long to convert

**Comment by odivinewraitho** [comment]
Hey, 

I'm having the same issue. Did you find a solution?

**Comment by metalicjames** [comment]
https://github.com/akhavr/electrum-dash/pull/42 looks like Dash's Electrum fork had a similar problem

**Comment by metalicjames** [comment]
Fixed in #101

**Comment by chknlegz** [comment]
Same issue happening with me even with version 3.2.2 RC2.  any ideas for me? funds are stuck.

**Comment by metalicjames** [comment]
Use 3.1.2 until 3.2.2.1 is released with the patch for this Windows issue.

**Comment by chknlegz** [comment]
when downgrading to 3.1.2, it tells me that the wallet versions are not compatible.  any idea when this will be released? I do not have knowledge on how to apply the patch manually.  Thanks!
